language: go
sudo: false
go:
  - 1.5.4
  - 1.6.1
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
script: go test github.com/3ofcoins/appc-metadata-client
matrix:
  allow_failures:
    - go: tip
